kind: ConfigMap
apiVersion: v1
metadata:
  name: jodiostestbotconfigmap
  namespace: prod
data:
  discordToken: #{secrets.discordToken}#
  plotlyToken: #{secrets.plotlyToken}#
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jodios-test-bot
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jodios-test-bot
  template:
    metadata:
      labels:
        app: jodios-test-bot 
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: jodios-test-bot-config
      containers:
        - name: jodios-test-bot
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /app/build/main/resources
          envFrom:
            - configMapRef:
                name: jodiostestbotconfigmap
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst