kind: ConfigMap
apiVersion: v1
metadata:
  name: jodiostestbotconfigmap
  namespace: prod
data:
  discordToken: #{secrets.discordToken}#
  plotlyToken: #{secrets.plotlyToken}#
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jodios-test-bot
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jodios-test-bot
  template:
    metadata:
      labels:
        app: jodios-test-bot 
    spec:
      volumes:
        - name: admin-key
          secret:
            secretName: jodios-test-bot-admin-key
        - name: config-volume
          configMap:
            name: jodios-test-bot-config
      containers:
        - name: jodios-test-bot
          image: #{deployment.image.name}#
          volumeMounts:
          - name: admin-key
            mountPath: /app/build/main/resources/admin-config.json
            subPath: admin-config.json
          - name: config-volume
            mountPath: /app/build/main/resources/config.json
            subPath: config.json
          envFrom:
            - configMapRef:
                name: jodiostestbotconfigmap
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst