apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sirsamhainjodiostestbot 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sirsamhainjodiostestbot 
    spec:
      containers:
        - name: sirsamhainjodiostestbot 
          image: discordregistry.azurecr.io/sirsamhainjodiostestbot
          ports:
          - containerPort: 8080